services:
  - type: web
    name: dehum-assistant
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 web_app:app"
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: USE_OPENAI
        value: "true"
      - key: REDIS_URL
        fromService:
          type: redis
          name: dehum-redis
          property: connectionString
  
  - type: redis
    name: dehum-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
