services:
  - type: web
    name: dehum-assistant
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python web_app.py
    envVars:
      - key: FLASK_SECRET_KEY
        value: supersecret
      - key: OPENAI_API_KEY
        sync: false  # add this manually
      - key: USE_OPENAI
        value: true
      - key: OLLAMA_HOST
        value: http://localhost:11434
      - key: OLLAMA_MODEL
        value: llama2
